global:
  mode: census
  pollIntervalMs: 1000
  quoteIntervalMs: 3000
  enableSingleHop: true
  enableTriangular: false
  enableCrossChain: false
  minNetUsd: 1.0
  pnlMultipleMin: 2.5
  revertProbability: 0.01
  inclusionTargetMs: 100
  maxEdgeAgeMs: 15000
  slippageBps: 30
  deadlineBufferSec: 120
  maxConcurrentExecutions: 2
  maxVenuesPerLeg: 1
chains:
  - chainId: 42161
    enabled: true
    nativeToken: WETH
    treasuryFloatUsd: 2000
    gasUnitsEstimate: 900000
    gasSafetyMultiplier: 1.25
    pairs:
      - id: arb-weth-usdc
        symbol: WETH/USDC
        baseToken: WETH
        quoteToken: USDC
        tradeSize:
          baseAmount: "0.25"
        venues:
          - id: univ3-500
            label: UniV3 0.05%
            kind: uniswap_v3
            feeBps: 500
          - id: univ3-3000
            label: UniV3 0.30%
            kind: uniswap_v3
            feeBps: 3000
  - chainId: 10
    enabled: true
    nativeToken: WETH
    treasuryFloatUsd: 2000
    gasUnitsEstimate: 900000
    gasSafetyMultiplier: 1.3
    pairs:
      - id: op-weth-usdc
        symbol: WETH/USDC
        baseToken: WETH
        quoteToken: USDC
        tradeSize:
          baseAmount: "0.25"
        venues:
          - id: univ3-500
            label: UniV3 0.05%
            kind: uniswap_v3
            feeBps: 500
          - id: univ3-3000
            label: UniV3 0.30%
            kind: uniswap_v3
            feeBps: 3000
  - chainId: 8453
    enabled: true
    nativeToken: WETH
    treasuryFloatUsd: 2000
    gasUnitsEstimate: 900000
    gasSafetyMultiplier: 1.3
    pairs:
      - id: base-weth-usdc
        symbol: WETH/USDC
        baseToken: WETH
        quoteToken: USDC
        tradeSize:
          baseAmount: "0.25"
        venues:
          - id: univ3-500
            label: UniV3 0.05%
            kind: uniswap_v3
            feeBps: 500
          - id: univ3-3000
            label: UniV3 0.30%
            kind: uniswap_v3
            feeBps: 3000
