contracts:
  liquidator:
    1: "0x..."
    42161: "0x..."
    10: "0x..."
    8453: "0x..."
    137: "0x..."

chains:
  - id: 1      # Ethereum mainnet
    name: ethereum
    rpc: ${RPC_ETH}
    wsRpc: ${WS_ETH}
    privtx: ${PRIVTX_ETH}
    aaveProvider: "0xa97684EaD0E402dC232d5A977953DF7ECBaB3CDb"
    uniV3Router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    quoter: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
    enabled: false
    tokens:
      USDC:
        address: "0xA0b86991C6218B36c1d19D4a2e9Eb0cE3606eB48"
        decimals: 6
        chainlinkFeed: "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6"
      DAI:
        address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
        decimals: 18
        chainlinkFeed: "0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9"
      USDT:
        address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
        decimals: 6
        chainlinkFeed: "0xEe9F2375b4bdF6387aa8265dD4FB8F16512A1d46"
      WETH:
        address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
        decimals: 18
        chainlinkFeed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
      WBTC:
        address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
        decimals: 8
        chainlinkFeed: "0xf4030086522a5beea4988f8ca5b36dbc97bee88c"
      stETH:
        address: "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"
        decimals: 18
        chainlinkFeed: "0xcfe54b5cd566ab89272946f602d76ea879cab4a8"

  - id: 42161   # Arbitrum
    name: arbitrum
    rpc: ${RPC_ARB}
    wsRpc: ${WS_ARB}
    privtx: ${PRIVTX_ARB}
    aaveProvider: "0xa97684EaD0E402dC232d5A977953DF7ECBaB3CDb"
    uniV3Router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    quoter: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
    sequencerFeed: "0xFdB631F5EE196F0ed6FAa767959853A9F217697D"
    enabled: true
    tokens:
      USDC:
        address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
        decimals: 6
        chainlinkFeed: "0x50834F3163758fcC1Df9973b6e91f0F0F0434aD3"
      WETH:
        address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
        decimals: 18
        chainlinkFeed: "0x639fe6ab55c921f74e7fac1ee960c0b6293ba612"
      AAVE:
        address: "0xba5DdD1f9d7F570dc94a51479a000E3BCE967196"
        decimals: 18
        chainlinkFeed: "0xaD1d5344AaDE45F43E596773Bcc4c423EAbdD034"
      RDNT:
        address: "0x3082CC23568Ea640225c2467653dB90e9250AaA0"
        decimals: 18
      weETH:
        address: "0x35751007a407ca6FEFfE80b3cB397736D2cf4dbe"
        decimals: 18
        chainlinkFeed: "0x517276B5972C4Db7E88B9F76Ee500E888a2D73C3"
      LUSD:
        address: "0x93b346b6BC2548dA6A1E7d98E9a421B42541425b"
        decimals: 18
        chainlinkFeed: "0xc8b3e2776260c7e7A9C158a2344776e65E10ceE8"
      rETH:
        address: "0xEC70Dcb4A1EFa46b8F2D97C310C9c4790ba5ffA8"
        decimals: 18
        chainlinkFeed: "0x256f33FC0110B1297f78f48524631D30B752480D"

  - id: 10      # Optimism
    name: optimism
    rpc: ${RPC_OP}
    wsRpc: ${WS_OP}
    privtx: ${PRIVTX_OP}
    aaveProvider: "0xa97684EaD0E402dC232d5A977953DF7ECBaB3CDb"
    uniV3Router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    quoter: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
    sequencerFeed: "0x371EAD81c9102C9BF4874A9075FFFf170F2Ee389"
    enabled: false
    tokens:
      USDC:
        address: "0x0B2c639c533813f4aa9d7837cAf62653d097Ff85"
        decimals: 6
        chainlinkFeed: "0x6379A975Ef93EC2bE87f56A02CCF8535dFAde201"
      WETH:
        address: "0x4200000000000000000000000000000000000006"
        decimals: 18
        chainlinkFeed: "0x13e3ee699d1909e989722e753853ae30b17e08c5"

  - id: 8453   # Base
    name: base
    rpc: ${RPC_BASE}
    wsRpc: ${WS_BASE}
    privtx: ${PRIVTX_BASE}
    aaveProvider: "0xe20fCBdBfFC4Dd138cE8b2E6FBb6CB49777ad64D"
    uniV3Router: "0x2626664c2603336E57B271c5C0b26F421741e481"
    quoter: "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a"
    sequencerFeed: "0xBCF85224fc0756B9Fa45aA7892530B47e10b6433"
    enabled: false
    tokens:
      USDC:
        address: "0x833589fCD6eDb6E08f4c7C32D4f71B54bdA02913"
        decimals: 6
        chainlinkFeed: "0x7e860098F58bBFC8648a4311b374B1D669a2bc6B"
      WETH:
        address: "0x4200000000000000000000000000000000000006"
        decimals: 18
        chainlinkFeed: "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70"

  - id: 137    # Polygon PoS
    name: polygon
    rpc: ${RPC_POLYGON}
    wsRpc: ${WS_POLYGON}
    privtx: ${PRIVTX_POLYGON}
    aaveProvider: "0xa97684EaD0E402dC232d5A977953DF7ECBaB3CDb"
    uniV3Router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    quoter: "0x61ffe014ba17989e743c5f6cb21bf9697530b21e"
    enabled: false
    tokens:
      USDC:
        address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
        decimals: 6
        chainlinkFeed: "0xfE4A8cc5b5B2366C1B58Bea3858e81843581b2F7"
      WETH:
        address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
        decimals: 18
        chainlinkFeed: "0xF9680D99D6C9589e2a93a78A04A279e509205945"
      USDT:
        address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
        decimals: 6
        chainlinkFeed: "0x0A6513e40db6EB1b165753AD52E80663aeA50545"
      DAI:
        address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
        decimals: 18
        chainlinkFeed: "0xFC539A559e170f848323e19dfD66007520510085"
      WBTC:
        address: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
        decimals: 8
        chainlinkFeed: "0xc907E116054Ad103354f2D350FD2514433D57F6f"
      LINK:
        address: "0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39"
        decimals: 18
        chainlinkFeed: "0xb33Eb0195e90B751b848F2249397243f4AEB45FF"
      wstETH:
        address: "0x03B54A6e9A984069379fae1A4fC4dBAE93B3bCCD"
        decimals: 18
      AAVE:
        address: "0xd6DF932A45C0f255f85145F286ea0B292B21C90B"
        decimals: 18
        chainlinkFeed: "0x72484B12719E23115761D5DA1646945632979bB6"
      GHST:
        address: "0x385EeAC5cB85A38A9A07A70c73e0a3271cfb54A7"
        decimals: 18
        chainlinkFeed: "0xe638249AF9642CdA55A92245525268482eE4C67b"
      WPOL:
        address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
        decimals: 18
        chainlinkFeed: "0xab594600376ec9fd91f8e885dadf0ce036862de0"
      MaticX:
        address: "0xFA68FB4628DFF1028cFEc22b4162FCcd0d45efB6"
        decimals: 18
      stMATIC:
        address: "0x3A58A54C066FdC0F2d55FC9c89F0415c92EBf3C4"
        decimals: 18
        chainlinkFeed: "0xd9FFdb71EbE7496cC440152d43986Aae0AB76665"
      DPI:
        address: "0x85955046DF4668e1DD369d2dE9f3AEb98Dd2a369"
        decimals: 18
        chainlinkFeed: "0xD9Cf6096463f5e0ECcCa6F83d05bEB25E5693590"
      SUSHI:
        address: "0x0b3F868E0BE5597D5DB7FEB59E1CADBB0Fdda50A"
        decimals: 18
      WMATIC:
        address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
        decimals: 18
        chainlinkFeed: "0xAB594600376Ec9fD91F8e885dADF0CE036862dE0"
      miMATIC:
        address: "0xa3Fa99A148fA48D14Ed51d610c367C61876997F1"
        decimals: 18
        chainlinkFeed: "0x1e2Ba4725c6847dC8304466c4eA25A872A7D43a8"
      CRV:
        address: "0x172370d5Cd63279eFa6d502DAB29171933a610AF"
        decimals: 18
        chainlinkFeed: "0x336584C8E6Dc19637A5b36206B1c79923111b405"
      BAL:
        address: "0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3"
        decimals: 18
        chainlinkFeed: "0xD106B538F2A868c28Ca1Ec7E298C3325E0251d66"
      agEUR:
        address: "0xE0B52e49357Fd4DAf2c15e02058DCE6BC0057db4"
        decimals: 18
        chainlinkFeed: "0x73366Fe0AA0Ded304479862808e02506FE556a98"

assets:
  USDC:
    floorBps: 10
    gapCapBps: 120
    slippageBps: 80
  WETH:
    floorBps: 15
    gapCapBps: 110
    slippageBps: 70
  USDT:
    floorBps: 10
    gapCapBps: 120
    slippageBps: 80
  DAI:
    floorBps: 10
    gapCapBps: 120
    slippageBps: 80
  WBTC:
    floorBps: 18
    gapCapBps: 120
    slippageBps: 70
  LINK:
    floorBps: 22
    gapCapBps: 140
    slippageBps: 80
  wstETH:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  weETH:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  stETH:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  AAVE:
    floorBps: 25
    gapCapBps: 150
    slippageBps: 90
  WPOL:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  WMATIC:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  miMATIC:
    floorBps: 18
    gapCapBps: 135
    slippageBps: 85
  CRV:
    floorBps: 25
    gapCapBps: 150
    slippageBps: 90
  BAL:
    floorBps: 25
    gapCapBps: 150
    slippageBps: 90
  agEUR:
    floorBps: 18
    gapCapBps: 135
    slippageBps: 85
  MaticX:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  stMATIC:
    floorBps: 20
    gapCapBps: 130
    slippageBps: 80
  GHST:
    floorBps: 25
    gapCapBps: 150
    slippageBps: 90
  DPI:
    floorBps: 25
    gapCapBps: 150
    slippageBps: 90
  SUSHI:
    floorBps: 25
    gapCapBps: 150
    slippageBps: 90

markets:
  - protocol: aavev3
    chainId: 1
    debtAsset: USDC
    collateralAsset: WETH
    closeFactorBps: 4850
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 1
    debtAsset: USDT
    collateralAsset: WETH
    closeFactorBps: 4850
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 1
    debtAsset: DAI
    collateralAsset: WETH
    closeFactorBps: 4850
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 1
    debtAsset: USDC
    collateralAsset: WBTC
    closeFactorBps: 4850
    bonusBps: 850
    enabled: false
  - protocol: compoundv3
    chainId: 8453
    debtAsset: USDC
    collateralAsset: WETH
    enabled: false
  - protocol: compoundv3
    chainId: 8453
    debtAsset: USDC
    collateralAsset: cbETH
    enabled: false
  - protocol: compoundv3
    chainId: 10
    debtAsset: USDC
    collateralAsset: WETH
    enabled: false
  - protocol: morphoblue
    chainId: 1
    debtAsset: USDC
    collateralAsset: WETH
    enabled: false
  - protocol: morphoblue
    chainId: 1
    debtAsset: USDC
    collateralAsset: WBTC
    enabled: false
  - protocol: radiant
    chainId: 42161
    debtAsset: USDC
    collateralAsset: WETH
    enabled: false
  - protocol: radiant
    chainId: 42161
    debtAsset: USDC
    collateralAsset: WBTC
    enabled: false
  - protocol: aavev3
    chainId: 42161
    debtAsset: USDC
    collateralAsset: WETH
    closeFactorBps: 4850
    bonusBps: 800
    enabled: true
  - protocol: aavev3
    chainId: 10
    debtAsset: USDC
    collateralAsset: WETH
    closeFactorBps: 4850
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 8453
    debtAsset: USDC
    collateralAsset: WETH
    closeFactorBps: 5000
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: WETH
    closeFactorBps: 5000
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: WBTC
    closeFactorBps: 5000
    bonusBps: 750
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: wstETH
    closeFactorBps: 5000
    bonusBps: 750
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: LINK
    closeFactorBps: 5000
    bonusBps: 900
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: AAVE
    closeFactorBps: 5000
    bonusBps: 1000
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: WPOL
    closeFactorBps: 5000
    bonusBps: 1000
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: stMATIC
    closeFactorBps: 5000
    bonusBps: 900
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: MaticX
    closeFactorBps: 5000
    bonusBps: 900
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDC
    collateralAsset: GHST
    closeFactorBps: 5000
    bonusBps: 1000
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDT
    collateralAsset: WETH
    closeFactorBps: 5000
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDT
    collateralAsset: WBTC
    closeFactorBps: 5000
    bonusBps: 750
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: USDT
    collateralAsset: WPOL
    closeFactorBps: 5000
    bonusBps: 1000
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: DAI
    collateralAsset: WETH
    closeFactorBps: 5000
    bonusBps: 800
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: DAI
    collateralAsset: WBTC
    closeFactorBps: 5000
    bonusBps: 750
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: DAI
    collateralAsset: WPOL
    closeFactorBps: 5000
    bonusBps: 1000
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: WETH
    collateralAsset: wstETH
    closeFactorBps: 5000
    bonusBps: 750
    enabled: false
  - protocol: aavev3
    chainId: 137
    debtAsset: WETH
    collateralAsset: WBTC
    closeFactorBps: 5000
    bonusBps: 750
    enabled: false


routing:
  prefer:
    1:
      USDC-WETH: ["UniV3:500","UniV3:3000"]
      USDT-WETH: ["UniV3:500"]
      DAI-WETH: ["UniV3:500"]
      USDC-WBTC: ["UniV3:3000"]
    42161:
      USDC-WETH: ["UniV3:500","UniV3:3000","Camelot"]
      LINK-USDC: ["UniV3:3000","UniV3:500"]
      wstETH-WETH: ["UniV3:500"]
    10:
      USDC-WETH: ["UniV3:500","UniV3:3000","Velodrome"]
      LINK-USDC: ["UniV3:3000","UniV3:500"]
      wstETH-WETH: ["Velodrome","UniV3:500"]
    8453:
      USDC-WETH: ["UniV3:500","UniV3:3000","Aerodrome"]
    137:
      USDC-WETH: ["UniV3:500","UniV3:3000"]
      USDC-WBTC: ["UniV3:3000","UniV3:500"]
      USDC-wstETH: ["UniV3:500"]
      USDC-LINK: ["UniV3:3000","UniV3:500"]
      USDC-AAVE: ["UniV3:3000","UniV3:500"]
      USDC-WPOL: ["UniV3:500","UniV3:3000"]
      USDC-stMATIC: ["UniV3:500","UniV3:3000"]
      USDC-MaticX: ["UniV3:500","UniV3:3000"]
      USDC-GHST: ["UniV3:500","UniV3:3000"]
      USDT-WETH: ["UniV3:500","UniV3:3000"]
      USDT-WBTC: ["UniV3:3000","UniV3:500"]
      USDT-WPOL: ["UniV3:500","UniV3:3000"]
      DAI-WETH: ["UniV3:500","UniV3:3000"]
      DAI-WBTC: ["UniV3:3000","UniV3:500"]
      DAI-WPOL: ["UniV3:500","UniV3:3000"]
      WETH-wstETH: ["UniV3:500"]

risk:
  gasCapUsd: 15
  failRateCap: 0.25
  pnlPerGasMin: 1.4
  pnlMultMin: 4
  maxAttemptsPerBorrowerHour: 6
  dryRun: false
  healthFactorMax: 0.985
  maxRepayUsd: 2500
  maxLiveExecutions: 150
  maxSessionNotionalUsd: 15000
  minNetUsd: 1.5
  maxRevertRate: 0.02
  targetP95Ms: 120
  chainSpendCapUsd: 4000
  gasTopupMinUsd: 1000
  depegMode: false
  volatility:
    sizeShrinkBp: 500
    minNetUsd: 3
  denyAssets: []

indexer:
  subgraphFirst: 1000
  dedupeMs: 60000
  pollMs: 200
  hfThreshold: 0.995

analysis:
  openaiKey: ${OPENAI_API_KEY}

dexRouters:
  1:
    uniV3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    tokens:
      USDC: "0xA0b86991C6218B36c1d19D4a2e9Eb0cE3606eB48"
      WETH: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  42161:
    uniV3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    camelotV2: "0xc873fEcbd354f5A56E00E710B90EF4201db2448d"
    tokens:
      USDC: "0xaf88d065e77c8cC2239327c5EdB3A432268e5831"
      WETH: "0x82Af49447D8a07e3Bd95BD0d56F35241523fBab1"
  10:
    uniV3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    velodrome: "0xa062aE8A9c5e11aaA026fc2670B0D65cCc8B2858"
    velodromeFactory: "0xF1046053aa5682b4F9a81b5481394DA16BE5FF5a"
    tokens:
      USDC: "0x0B2c639c533813f4aa9d7837cAf62653d097Ff85"
      WETH: "0x4200000000000000000000000000000000000006"
  8453:
    uniV3: "0x2626664c2603336E57B271c5C0b26F421741e481"
    aerodrome: "0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43"
    aerodromeFactory: "0x420DD381b31aEf6683db6B902084cB0FFECe40Da"
    tokens:
      USDC: "0x833589fCD6eDb6E08f4c7C32D4f71B54bdA02913"
      WETH: "0x4200000000000000000000000000000000000006"
  137:
    uniV3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    camelotV2: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
    tokens:
      USDC: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
      WETH: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
      USDT: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
      DAI: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
      WBTC: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
      LINK: "0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39"
      wstETH: "0x03B54A6e9A984069379fae1A4fC4dBAE93B3bCCD"
      AAVE: "0xd6DF932A45C0f255f85145F286ea0B292B21C90B"
      GHST: "0x385EeAC5cB85A38A9A07A70c73e0a3271cfb54A7"
      WPOL: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
  WMATIC: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
      MaticX: "0xFA68FB4628DFF1028cFEc22b4162FCcd0d45efB6"
      stMATIC: "0x3A58A54C066FdC0F2d55FC9c89F0415c92EBf3C4"
      DPI: "0x85955046DF4668e1DD369d2dE9f3AEb98Dd2a369"
      SUSHI: "0x0b3F868E0BE5597D5DB7FEB59E1CADBB0Fdda50A"
  miMATIC: "0xa3Fa99A148fA48D14Ed51d610c367C61876997F1"
  CRV: "0x172370d5Cd63279eFa6d502DAB29171933a610AF"
  BAL: "0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3"
  agEUR: "0xE0B52e49357Fd4DAf2c15e02058DCE6BC0057db4"
