global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'orchestrator-worker'
    static_configs:
      - targets: ['worker:9464']
  - job_name: 'orchestrator-host'
    static_configs:
      - targets: ['host.docker.internal:9464']
  - job_name: 'risk-engine'
    metrics_path: /metrics
    static_configs:
      - targets: ['risk-engine:9465']
  # Risk engine exposes its own HTTP API for thresholds/feedback on 4010.
  # It does not expose Prometheus metrics; health can be monitored externally.
  # Uncomment below if a metrics endpoint is added later.
  # - job_name: 'risk-engine'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['host.docker.internal:9465']
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
