server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: orchestrator
          __path__: /var/lib/docker/containers/*/*-json.log
  - job_name: dryrun-files
    static_configs:
      - targets: ['localhost']
        labels:
          job: dryrun
          source: human
          __path__: /logs/dryrun_*.log
      - targets: ['localhost']
        labels:
          job: dryrun
          source: json
          __path__: /logs/dryrun_*.jsonl
      - targets: ['localhost']
        labels:
          job: dryrun
          source: live
          __path__: /logs/live.log
